package com.thencproject.papership.bind;

import com.thencproject.papership.annotations.PluginConfigurationFile;
import com.thencproject.papership.annotations.PluginDependency;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;
import javax.tools.FileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.Set;

@SupportedAnnotationTypes("de.einnik.boilerPlate.annotations.PluginConfigurationFile")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public class PluginYamlProcessor extends AbstractProcessor {

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }

        for (Element element : roundEnv.getElementsAnnotatedWith(PluginConfigurationFile.class)) {
            if (element.getKind() != ElementKind.CLASS) {
                processingEnv.getMessager().printMessage(
                        Diagnostic.Kind.ERROR,
                        "@PluginConfigurationFile can only be applied to classes",
                        element
                );
                continue;
            }

            TypeElement classElement = (TypeElement) element;
            PluginConfigurationFile config = element.getAnnotation(PluginConfigurationFile.class);

            try {
                assert config != null;
                generatePaperPluginYml(config, classElement);
            } catch (IOException e) {
                processingEnv.getMessager().printMessage(
                        Diagnostic.Kind.ERROR,
                        "Failed to generate paper-plugin.yml: " + e.getMessage(),
                        element
                );
            }
        }
        return true;
    }

    private void generatePaperPluginYml(PluginConfigurationFile config, TypeElement classElement)
            throws IOException {

        FileObject resource = processingEnv.getFiler().createResource(
                StandardLocation.CLASS_OUTPUT,
                "",
                "paper-plugin.yml"
        );

        try (Writer writer = resource.openWriter()) {
            writer.write("# Auto-generated by BoilerPlate API\n");
            writer.write("# Source: " + classElement.getQualifiedName() + "\n");
            writer.write("# DO NOT EDIT MANUALLY\n\n");

            writer.write("name: " + config.name() + "\n");
            writer.write("version: " + config.version() + "\n");
            writer.write("main: " + classElement.getQualifiedName() + "\n");
            writer.write("api-version: '" + config.apiVersion() + "'\n");
            writer.write("load: " + config.loading().name() + "\n");

            if (!config.author().equals("[]")) {
                writer.write("authors: [" + config.author() + "]\n");
            }
            if (!config.description().isEmpty()) {
                writer.write("description: '" + escapeYaml(config.description()) + "'\n");
            }
            if (!config.website().isEmpty()) {
                writer.write("website: '" + escapeYaml(config.website()) + "'\n");
            }

            if (config.dependencies().length > 0) {
                writer.write("\ndependencies:\n");
                writer.write("  server:\n");

                for (PluginDependency dep : config.dependencies()) {
                    writer.write("    " + dep.name() + ":\n");

                    writer.write("      load: " + (dep.load() ? "BEFORE" : "AFTER") + "\n");
                    writer.write("      required: " + dep.required() + "\n");

                    if (dep.joinClasspath()) {
                        writer.write("      join-classpath: true\n");
                    }
                }
            }
        }
    }

    private String escapeYaml(String value) {
        return value.replace("'", "''");
    }
}